### PR TITLE
feat(cli): Add converted templates

### PR DESCRIPTION
**Pull request by aloisdg**
| template       | valid name  | valid content | note                              |
|:----------------|:----------------|:----------------|:------------------------------|
| bbedit |  :white_check_mark: | :white_check_mark: | |
| chrome-devtools |  :white_check_mark: | :white_check_mark: | |
| codemirror |  :white_check_mark: | :white_check_mark: | |
| connectbot |  :white_check_mark: | :white_check_mark: | |
| dmenu |  :white_check_mark: | :white_check_mark: | |
| emacs |  :white_check_mark: | :white_check_mark: | |
| geany |  :white_check_mark: | :white_check_mark: | |
| gedit |  :white_check_mark: | :white_check_mark: | |
| gnome-terminal |  :white_check_mark: | :white_check_mark: | |
| guake |  :white_check_mark: | :white_check_mark: | |
| highlighting-kate |  :white_check_mark: | :white_check_mark: | |
| highlight.js |  :white_check_mark: | :white_check_mark: | |
| highlight.js-less |  :white_check_mark: | :white_check_mark: | |
| highlight.js-sass |  :white_check_mark: | :white_check_mark: | |
| highlight.js-stylus |  :white_check_mark: | :white_check_mark: | |
| idea |  :white_check_mark: | :white_check_mark: | |
| ipython-notebook |  :white_check_mark: | :white_check_mark: | |
| iterm2 |  :white_check_mark: | :white_check_mark: | |
| jupyter-notebook |  :white_check_mark: | :white_check_mark: | |
| mate-terminal |  :white_check_mark: | :white_check_mark: | |
| mmdc2 |  :white_check_mark: | :white_check_mark:  | |
| mobaxterm |  :white_check_mark: | :white_check_mark: | |
| monodevelop |  :white_check_mark: | :white_check_mark: | |
| mou |  :white_check_mark: | :white_check_mark: | We lost dark+ and light+ |
| mutt |  :white_check_mark: | :white_check_mark: | |
| notepad-plus-plus |  :white_check_mark: | :white_check_mark: | |
| pantheon-terminal |  :white_check_mark: | :white_check_mark: | |
| prettify.js |  :white_check_mark: | :white_check_mark: | |
| prettify.js-less |  :white_check_mark: | :white_check_mark: | |
| prettify.js-sass |  :white_check_mark: | :white_check_mark: | |
| prettify.js-stylus |  :white_check_mark: | :white_check_mark: | |
| prism |  :white_check_mark: | :white_check_mark: | |
| prism-less |  :white_check_mark: | :white_check_mark: | |
| prism-sass |  :white_check_mark: | :white_check_mark: | |
| prism-stylus |  :white_check_mark: | :white_check_mark: | |
| qtcreator |  :white_check_mark: | :white_check_mark: | |
| rainbow |  :white_check_mark: | :white_check_mark: | |
| rainbow-less |  :white_check_mark: | :white_check_mark: | |
| rainbow-sass |  :white_check_mark: | :white_check_mark: | |
| rainbow-stylus |  :white_check_mark: | :white_check_mark: | |
| roxterm |  :white_check_mark: | :x: | ruby code |
| rxvt-unicode |  :white_check_mark: | :white_check_mark: | |
| secure-shell |  :white_check_mark: | :white_check_mark: | |
| shell |  :white_check_mark: | :white_check_mark: | |
| st |  :white_check_mark: | :white_check_mark: | |
| terminal-app |  :white_check_mark: | :x: | ruby code |
| terminator |  :white_check_mark: | :white_check_mark: | |
| termite |  :white_check_mark: | :white_check_mark: | |
| textadept |  :white_check_mark: | :white_check_mark: | |
| textmate |  :white_check_mark: | :white_check_mark: | |
| vconsole |  :white_check_mark: | :white_check_mark: | |
| visual-studio |  :white_check_mark: | :white_check_mark: | |
| xcode |  :white_check_mark: | :white_check_mark:  | |
| xfce4-terminal |  :x: | :white_check_mark: | rename inner files to match spec |
| xresources |  :white_check_mark: | :white_check_mark: | |
| zathura |  :white_check_mark: | :white_check_mark: | |
| atom | :x: |  :white_check_mark: | rename inner files to match spec |
| conemu | :white_check_mark: |  :white_check_mark: | a review would be nice |
| console2 | :white_check_mark:  |  :white_check_mark: | implement light with lumos |
| drracket | :white_check_mark:  |  :white_check_mark: | file contains both light and dark |
| gimp-palette | :white_check_mark: |  :white_check_mark: | unrelated to luminosity so both |
| i3 | :white_check_mark: |  :white_check_mark: | Add light theme myself |
| i3status |  :white_check_mark: |  :white_check_mark: | unrelated to luminosity so both |
| i3-style | :white_check_mark:  |  :white_check_mark: | Add light theme myself |
| konsole |  :x: | :x: | contains 3 files with ruby code |
| less | :white_check_mark: |  :white_check_mark: | unrelated to luminosity so both |
| mintty | :white_check_mark: |  :white_check_mark: | missing light I guess |
| powerpaint | :x: |  :x: | ruby code |
| preview | :x: |  :white_check_mark: | rename inner files to match spec |
| putty | :white_check_mark: |  :white_check_mark: | implement light with lumos |
| pygments | :white_check_mark: |  :white_check_mark: | split in two folders : css & py |
| rouge | :white_check_mark: |  :white_check_mark: | unrelated to luminosity so both |
| sass | :white_check_mark: |  :white_check_mark: | unrelated to luminosity so both |
| smartftp | :white_check_mark: |  :white_check_mark: | implement light with lumos  |
| stylus | :white_check_mark: |  :white_check_mark: | unrelated to luminosity so both |
| tex-xcolor | :white_check_mark: |  :white_check_mark: | unrelated to luminosity so both |
| vim-airline | :x: |  :white_check_mark: | rename inner files to match spec |
| vim | :x: |  :x: | `{{ slug(@scheme) }}` is it valid? |
| windows-command-prompt | :white_check_mark:  |  :white_check_mark: | unrelated to luminosity so both |

=========

- [x] [bbedit](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/bbedit)
- [x] [chrome-devtools](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/chrome-devtools)
- [x] [codemirror](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/codemirror)
- [x] [connectbot](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/connectbot)
- [x] [dmenu](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/dmenu)
- [x] [emacs](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/emacs)
- [x] [geany](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/geany)
- [x] [gedit](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/gedit)
- [x] [gnome-terminal](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/gnome-terminal)
- [x] [guake](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/guake)
- [x] [highlighting-kate](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/highlighting-kate)
- [x] [highlight.js](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/highlight.js)
- [x] [highlight.js-less](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/highlight.js-less)
- [x] [highlight.js-sass](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/highlight.js-sass)
- [x] [highlight.js-stylus](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/highlight.js-stylus)
- [x] [idea](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/idea)
- [x] [ipython-notebook](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/ipython-notebook)
- [x] [iterm2](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/iterm2)
- [x] [jupyter-notebook](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/jupyter-notebook)
- [x] [mate-terminal](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/mate-terminal)
- [x] [mmdc2](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/mmdc2)
- [x] [mobaxterm](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/mobaxterm)
- [x] [monodevelop](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/monodevelop)
- [x] [mou](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/mou)
- [x] [mutt](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/mutt)
- [x] [notepad-plus-plus](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/notepad-plus-plus)
- [x] [pantheon-terminal](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/pantheon-terminal)
- [x] [prettify.js](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prettify.js)
- [x] [prettify.js-less](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prettify.js-less)
- [x] [prettify.js-sass](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prettify.js-sass)
- [x] [prettify.js-stylus](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prettify.js-stylus)
- [x] [prism](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prism)
- [x] [prism-less](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prism-less)
- [x] [prism-sass](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prism-sass)
- [x] [prism-stylus](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/prism-stylus)
- [x] [qtcreator](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/qtcreator)
- [x] [rainbow](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/rainbow)
- [x] [rainbow-less](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/rainbow-less)
- [x] [rainbow-sass](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/rainbow-sass)
- [x] [rainbow-stylus](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/rainbow-stylus)
- [ ] [roxterm](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/roxterm)
- [x] [rxvt-unicode](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/rxvt-unicode)
- [x] [secure-shell](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/secure-shell)
- [x] [shell](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/shell)
- [x] [st](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/st)
- [ ] [terminal-app](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/terminal-app)
- [x] [terminator](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/terminator)
- [x] [termite](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/termite)
- [x] [textadept](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/textadept)
- [x] [textmate](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/textmate)
- [x] [vconsole](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/vconsole)
- [x] [visual-studio](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/visual-studio)
- [x] [xcode](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/xcode)
- [ ] [xfce4-terminal](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/xfce4-terminal)
- [x] [xresources](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/xresources)
- [x] [zathura](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/zathura)
- [ ] [atom](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/atom)
- [x] [conemu](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/conemu)
- [x] [console2](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/console2)
- [x] [drracket](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/drracket)
- [x] [gimp-palette](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/gimp-palette)
- [x] [i3](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/i3)
- [x] [i3status](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/i3status)
- [x] [i3-style](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/i3-style)
- [ ] [konsole](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/konsole)
- [x] [less](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/less)
- [x] [mintty](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/mintty)
- [ ] [powerpaint](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/powerpaint)
- [ ] [preview](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/preview)
- [x] [putty](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/putty)
- [x] [pygments.css](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/pygments.css)
- [x] [pygments.py](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/pygments.py)
- [x] [rouge](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/rouge)
- [x] [sass](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/sass)
- [x] [smartftp](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/smartftp)
- [x] [stylus](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/stylus)
- [x] [tex-xcolor](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/tex-xcolor)
- [ ] [vim-airline](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/vim-airline)
- [ ] [vim](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/vim)
- [x] [windows-command-prompt](https://github.com/aloisdg/base16-builder/tree/templates/db/templates/windows-command-prompt)

### CODE REVIEW

**Comment by alexbooker** [comment]
So far, so good. Thanks, @aloisdg!

Hm. I noticed some files are called template/dark.256. Shouldn't it be template/dark-256?

**Comment by aloisdg** [comment]
@alexbooker Good catch. Fixed it in #6311a38

**Comment by alexbooker** [comment]
I'm looking at the _`connectbot`_  template:



_`connectbot`_ is the only template that mentions _"16"_.

I do not think the number _"16"_ should appear in the file name as 16 is the default.

**Comment by aloisdg** [comment]
> I do not think the number "16" should appear in the file name as 16 is the default.

So should I remove it?

**Comment by alexbooker** [comment]
> So should I remove it?

Unless you foresee a problem... Yes.

**Comment by aloisdg** [comment]
> > So should I remove it?

> Unless you foresee a problem... Yes.

[Done.](https://github.com/aloisdg/base16-builder/commit/682852be4198a934d3654ae3fe038984b6e9a879)

**Pull request merged**
